package evenfib;

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

// TARGET ANSWER: 4613732
// COMMIT ANSWER: 4613732
public class Euler2 {
    public static void main(String[] args) {
        int limit = 4000000;

        solution(limit);
    }

    static void solution(int n) {
        int n1 = 1;
        int n2 = 2;
        int sum = 0;

        while (n1 <= n) {
            if (n1 %2 == 0) {
                sum += n1;
            }
            int n3 = n1 + n2;
            n1 = n2;
            n2 = n3;
        }
        System.out.println(sum);
    }
}
